# Generated by Django 3.2.11 on 2022-01-13 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mallname', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='쇼핑몰 이름')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='제목')),
                ('price', models.CharField(db_index=True, max_length=100, verbose_name='가격')),
                ('link', models.CharField(db_index=True, max_length=100, verbose_name='링크')),
                ('content', models.TextField(verbose_name='내용')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
